// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALD78uqeKT8D9Q3kRqVWDdBloRrcmky_g',
    appId: '1:496480783560:web:df27348ab99415c5fda9fd',
    messagingSenderId: '496480783560',
    projectId: 'employee-c0508',
    authDomain: 'employee-c0508.firebaseapp.com',
    storageBucket: 'employee-c0508.firebasestorage.app',
    measurementId: 'G-1YTEBP5G10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB6tg78MXSCQ5_FMU2o7aC7704qoCeo0A',
    appId: '1:496480783560:android:102b5d4fcefb46d5fda9fd',
    messagingSenderId: '496480783560',
    projectId: 'employee-c0508',
    storageBucket: 'employee-c0508.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAns-6OZEoxqRSWQqdAXnWIGUcWE3UndGY',
    appId: '1:496480783560:ios:d81cdd0d3ab7b184fda9fd',
    messagingSenderId: '496480783560',
    projectId: 'employee-c0508',
    storageBucket: 'employee-c0508.firebasestorage.app',
    iosBundleId: 'com.example.flutterEmployee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAns-6OZEoxqRSWQqdAXnWIGUcWE3UndGY',
    appId: '1:496480783560:ios:d81cdd0d3ab7b184fda9fd',
    messagingSenderId: '496480783560',
    projectId: 'employee-c0508',
    storageBucket: 'employee-c0508.firebasestorage.app',
    iosBundleId: 'com.example.flutterEmployee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALD78uqeKT8D9Q3kRqVWDdBloRrcmky_g',
    appId: '1:496480783560:web:5ed8fbc9db9e6747fda9fd',
    messagingSenderId: '496480783560',
    projectId: 'employee-c0508',
    authDomain: 'employee-c0508.firebaseapp.com',
    storageBucket: 'employee-c0508.firebasestorage.app',
    measurementId: 'G-862JHDYM5K',
  );
}
